const String _germanPlateRegionCodeData = '''
A AA ABG ABI AC AE AH AIC AK ALF ALZ AM ANA ANG ANK AÖ AP APD ARN ART AS ASL
ASZ AT AU AUR AW AZ AZE B BAD BAR BB BBG BBL BC BCH BD BE BED BEL BER BF BGD
BGL BI BID BIN BIR BIT BIW BKS BL BLB BLK BM BN BNA BO BÖ BOG BOH BOR BOT BP
BR BRA BRB BRG BRK BRL BRV BSB BSK BTF BÜD BÜR BÜZ BW BWL BYL BZ C CA CAS CB
CE CHA CLP CLZ CO COC COE CR CUX CW D DA DAH DAN DAU DBR DE DEG DEL DGF DH DI
DIL DIN DIZ DKB DL DLG DM DN DO DON DS DT DU DUD DÜW DW DZ E EA EB EBE EBN
ECK ED EE EF EG EH EI EIC EIL EIN EIS EL EM EMD EMS EN ER ERB ERH ERK ERZ ES
ESW EU EW F FB FD FDB FDS FEU FF FFB FG FI FKB FL FLÖ FN FO FOR FRG FRI FRW
FS FT FTL FÜS FW FZ G GA GAN GAP GC GD GDB GE GEL GER GF GG GHA GHC GI GK GL
GLA GM GMN GN GNT GOA GOH GP GR GRA GRH GRM GRZ GS GT GTH GÜ GUB GUN GV GVM
GW GZ H HA HAB HAL HAM HAS HB HBN HBS HC HDH HDL HE HEB HEF HEI HEL HER HET HF HG
HGN HGW HH HHM HI HIG HIP HK HL HM HMÜ HOG HOH HOL HOM HOR HÖS HOT HP HR HRO
HS HSK HST HV HVL HWI HX HY HZ IGB IK IL ILL IN IZ J JB JE JL JÜL K KB KC KE
KEH KEL KF KG KH KI KIB KK KLE KLZ KM KN KO KÖN KÖT KÖZ KR KRU KS KT KU KÜN
KUS KW KY KYF L LAN LAU LB LBS LBZ LC LD LDK LDS LE LEO LER LEV LG LH LI LIB
LIF LIP LK LL LM LN LÖ LÖB LOS LP LR LRO LSA LSN LSZ LU LUK LÜN LUP LWL M MA
MAB MAK MB MC MD ME MED MEG MEI MEK MEL MER MET MG MGH MGN MH MHL MI MIL MK
MKK ML MM MN MO MOD MOL MON MOS MQ MR MS MSE MSH MSP MST MTK MTL MU MÜ MUC MÜL
MÜR MVL MW MY MYK MZG N NAI NAU NB ND NDH NE NEA NEB NEC NEN NES NEU NEW NF
NH NI NK NL NM NMB NMS NÖ NOH NOL NOM NOR NP NR NRW NT NU NVP NW NWM NY NZ OA
OAL OB OBB OBG OC OCH OD OE OF OG OH OHA ÖHR OHV OHZ OK OP OPR OSL OTW OVI
OVL OZ P PAF PAN PB PCH PE PI PIR PL PLÖ PM PN PR PRÜ PW PZ QFT QLB R RA RC RD
RDG RE REG REI RG RH RI RID RIE RL RM RN ROF ROK ROS ROT ROW RP RPL RS RSL RT
RU RÜD RÜG RV RW RZ S SAB SAD SÄK SAL SAW SB SBG SBK SC SCZ SDH SDL SDT SE SEB
SEE SEF SEL SFB SFT SG SGH SH SHA SHG SHK SHL SI SIG SIM SK SL SLE SLF SLK SLN
SLS SLÜ SLZ SM SMÜ SN SO SOB SOG SOK SÖM SON SP SPB SPN SRB SRO ST STA STB STD
STE STL SU SUL SÜW SWA SY SZ SZB TBB TDO TE TET TF TG THL THW TIR TO TÖL TP
TR TS TT TÜ TUT UE UEM UFF UH UM UN USI V VAI VB VEC VER VG VIE VIT VK VOH VR
VS W WA WAF WAK WAN WAR WAT WB WBS WDA WE WEL WEN WES WF WG WHV WI WIL WIS
WIT WIZ WK WL WLG WM WMS WN WND WO WOB WOH WOS WR WRN WSF WST WSW WT WTL WTM
WUG WÜM WUN WUR WW WZ WZL X Y Z ZE ZEL ZI ZIG ZP ZR ZS ZZ
''';

final Map<String, String> germanPlateRegionCodesBySpeechKey = {
  for (final code
      in _germanPlateRegionCodeData
          .split(RegExp(r'\s+'))
          .where((value) => value.isNotEmpty))
    _toSpeechKey(code): code,
};

String _toSpeechKey(String value) {
  return value
      .trim()
      .toUpperCase()
      .replaceAll('Ä', 'AE')
      .replaceAll('Ö', 'OE')
      .replaceAll('Ü', 'UE');
}
