// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOv-zud409BruVEHwM7kmjWnyi9OBr0eA',
    appId: '1:493803183324:web:7f020f8de3d24360896819',
    messagingSenderId: '493803183324',
    projectId: 'carma-a84e4',
    authDomain: 'carma-a84e4.firebaseapp.com',
    storageBucket: 'carma-a84e4.firebasestorage.app',
    measurementId: 'G-4PB36F0ZWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs4N5ra1m3IATkyY317ZrwrKKy91gR9Sg',
    appId: '1:493803183324:android:c385f30944ec2804896819',
    messagingSenderId: '493803183324',
    projectId: 'carma-a84e4',
    storageBucket: 'carma-a84e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCugKy_9EquDztsLjqyY5vzShiUl4QGm5w',
    appId: '1:493803183324:ios:9c92e2a694aba958896819',
    messagingSenderId: '493803183324',
    projectId: 'carma-a84e4',
    storageBucket: 'carma-a84e4.firebasestorage.app',
    iosBundleId: 'com.example.carma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCugKy_9EquDztsLjqyY5vzShiUl4QGm5w',
    appId: '1:493803183324:ios:9c92e2a694aba958896819',
    messagingSenderId: '493803183324',
    projectId: 'carma-a84e4',
    storageBucket: 'carma-a84e4.firebasestorage.app',
    iosBundleId: 'com.example.carma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOv-zud409BruVEHwM7kmjWnyi9OBr0eA',
    appId: '1:493803183324:web:bf752a625745c6c4896819',
    messagingSenderId: '493803183324',
    projectId: 'carma-a84e4',
    authDomain: 'carma-a84e4.firebaseapp.com',
    storageBucket: 'carma-a84e4.firebasestorage.app',
    measurementId: 'G-1GKX7EQZMR',
  );
}
